from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, EmailStr


class AgencyFeatures(BaseModel):
    essay_agent: bool = Field(default=False)
    deadline_watchdog: bool = Field(default=False)


class AgencySettings(BaseModel):
    plan: str = Field(default="free", description="Subscription plan name")
    features: AgencyFeatures = Field(default_factory=AgencyFeatures)


class AgencyCreateRequest(BaseModel):
    name: str
    slug: str
    status: str = "active"
    settings: AgencySettings = Field(default_factory=AgencySettings)


class AgencyUpdateRequest(BaseModel):
    name: Optional[str] = None
    slug: Optional[str] = None
    status: Optional[str] = None
    settings: Optional[AgencySettings] = None


class AgencyResponse(BaseModel):
    agency_id: str
    name: str
    slug: str
    status: str
    settings: AgencySettings
    created_at: datetime
    updated_at: datetime


class AgencyOut(BaseModel):
    agency_id: str
    name: str
    slug: str
    status: str
    settings: AgencySettings
    created_at: datetime
    updated_at: datetime


class AgencyListResponse(BaseModel):
    AgencyList: List[AgencyResponse]


# Agency Member related schemas
class AgencyMember(BaseModel):
    member_id: str
    user_id: str
    email: str
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    role: str
    status: str
    permissions: List[str] = []
    joined_at: datetime
    last_active_at: Optional[datetime] = None


class AgencyMemberListResponse(BaseModel):
    members: List[AgencyMember]
    total: int
    page: int
    page_size: int
    has_next: bool
    has_prev: bool


class AgencyMemberQueryRequest(BaseModel):
    role: Optional[str] = None
    status: Optional[str] = None
    search: Optional[str] = None
    page: int = 1
    page_size: int = 10


class InviteMemberRequest(BaseModel):
    email: str
    role: Optional[str] = None
    permissions: Optional[List[str]] = None


class UpdateMemberRequest(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None
    email: Optional[str] = None
    role: Optional[str] = None
    status: Optional[str] = None
    permissions: Optional[List[str]] = None


class InviteContractedTeacherRequest(BaseModel):
    """Request model for inviting a contracted teacher"""

    email: EmailStr = Field(..., description="Email to send invite to")
    teacher_id: Optional[str] = Field(
        None, description="Teacher ID (generated by backend if not provided)"
    )
    contract_start_date: Optional[datetime] = Field(
        None, description="Contract start date"
    )
    message: Optional[str] = Field(None, description="Invitation message")
