from typing import List, Optional

from pydantic import BaseModel, Field
from datetime import datetime

from .token_schema import TokenResponse


class Membership(BaseModel):
    tenant_id: Optional[str] = Field(
        None,
        description="Tenant ID for organization-specific roles, null for global roles",
    )
    role: str = Field(..., description="User role (students, admin, admit, etc.)")
    abilities: List[str] = Field(
        ..., description="List of permissions/abilities for this role"
    )
    status: str = Field(
        ..., description="Membership status (active, inactive, pending)"
    )


class SignUpRequest(BaseModel):
    email: str = Field(..., description="User email address")
    password: str = Field(
        min_length=8,
        example="secret123",
        description="User password (minimum 8 characters)",
    )
    memberships: List[Membership] = Field(
        ..., description="List of users memberships with roles and permissions"
    )


class SignUpResponse(BaseModel):
    user_id: str = Field(..., description="Unique users identifier")
    email: str = Field(..., description="User email address")
    memberships: List[Membership] = Field(
        ..., description="List of users memberships with roles and permissions"
    )
    token: TokenResponse = Field(..., description="Authentication tokens")
    created_at: datetime = Field(..., description="Account creation timestamp")
    updated_at: datetime = Field(..., description="Last update timestamp")


class LoginRequest(BaseModel):
    email: str = Field(..., description="User email address")
    password: str = Field(..., description="User password")


class LoginResponse(BaseModel):
    user_id: str = Field(..., description="Unique user identifier")
    email: str = Field(..., description="User email address")
    token: TokenResponse = Field(..., description="Authentication tokens")


class ResetPasswordRequest(BaseModel):
    email: str = Field(..., description="User email address")
    password: str = Field(
        ..., min_length=8, description="New password (minimum 8 characters)"
    )
    code: str = Field(..., description="Email verification code")


class GuestLoginRequest(BaseModel):
    user_id: str = Field(..., description="Guest user ID generated by frontend")


class GuestLoginResponse(BaseModel):
    user_id: str = Field(..., description="Guest user identifier")
    token: TokenResponse = Field(..., description="Authentication tokens")


class RefreshTokenRequest(BaseModel):
    user_id: str = Field(..., description="User identifier")
    refresh_token: str = Field(..., description="Refresh token for authentication")


class SendCodeRequest(BaseModel):
    email: str = Field(..., description="User email address")
    purpose: str = Field(
        ...,
        description="Purpose of the verification code (must match SIGN_UP_VERIFICATION_EMAIL or RESET_PASSWORD_VERIFICATION_EMAIL from config)",
    )


class VerifyEmailCodeRequest(BaseModel):
    email: str = Field(..., description="User email address")
    purpose: str = Field(
        ...,
        description="Purpose of the verification code (must match SIGN_UP_VERIFICATION_EMAIL or RESET_PASSWORD_VERIFICATION_EMAIL from config)",
    )
    code: str = Field(..., description="Email verification code")


class SetPasswordRequest(BaseModel):
    email: str = Field(..., description="User email address")
    password: str = Field(
        ..., min_length=8, description="New password (minimum 8 characters)"
    )


class MessageResponse(BaseModel):
    message: str
    timestamp: Optional[datetime] = None
